name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build container
      uses: docker/build-push-action@v2

  push:
    if: github.event_name != 'pull_request'
    needs:
    - container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Determine SHA
      id: sha
      run: echo "::set-output name=sha::$(git describe --always --tags --dirty)"
    - name: Build and push
      id: push
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/arm64, linux/arm, linux/amd64
        tags: squat/cpiped:latest, squat/cpiped:${{ steps.sha.outputs.sha }}
    - name: Determine digest
      run: echo ${{ steps.push.outputs.digest }}
